In [1]:
import pandas as pd
import bz2
import json

In [2]:
DATA_FOLDER = './'
SPEAKER_ATTRIBUTES_DATA = DATA_FOLDER+"speaker_attributes.parquet"

KNOWN_SPEAKER = DATA_FOLDER+"100000_knownspeakers_2019"
KNOWN_SPEAKER_DATA = KNOWN_SPEAKER+".json.bz2"
RETURN_FILE_DATA = KNOWN_SPEAKER+"_with_attributes.json.bz2"

In [3]:
#Read the parquet file and the dataframe (sampled as wished beforehand) to add the speakers attributes to
parquet = pd.read_parquet(SPEAKER_ATTRIBUTES_DATA)
df = pd.read_json(KNOWN_SPEAKER_DATA)

In [4]:
#Only the first speaker of each citations (the one with higher probability) is looked at
df['qids'] = df['qids'].apply(lambda x: x[0])

In [5]:
#Create a new dataframe with only the informations needed from the parquet file
parquet_new = parquet.get(['gender','date_of_birth','occupation','id'])
parquet_new.rename(columns={'id':'qids'}, inplace=True)

/Users/potdevinjosephine/opt/anaconda3/envs/ada/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [6]:
#Create the new dataframe with the additionnal informations about the speakers (gender, age, occupation)
df_new = df.merge(parquet_new)
df_new

,quoteID,quotation,speaker,qids,date,numOccurrences,probas,urls,phase,gender,date_of_birth,occupation
0,2019-04-08-048753,It is immoral. It is harmful. It is hurtful.,President Donald Trump,Q22686,2019-04-08 16:22:00,44,"[[President Donald Trump, 0.5802], [None, 0.36...",[https://www.mercedsunstar.com/news/business/a...,E,[Q6581097],[+1946-06-14T00:00:00Z],"[Q911554, Q557880, Q3427922, Q15980158, Q13152..."
1,2019-05-26-025817,It is where they want to be and where they sho...,President Donald Trump,Q22686,2019-05-26 15:37:49,3,"[[President Donald Trump, 0.6408], [None, 0.35...",[http://www.breitbart.com/news/trump-vows-roll...,E,[Q6581097],[+1946-06-14T00:00:00Z],"[Q911554, Q557880, Q3427922, Q15980158, Q13152..."
2,2019-03-20-001438,"a horrible, disgraceful thing and a horrible act.",President Donald Trump,Q22686,2019-03-20 16:36:57,5,"[[President Donald Trump, 0.871], [None, 0.129]]",[https://www.factcheck.org/2019/03/the-facts-o...,E,[Q6581097],[+1946-06-14T00:00:00Z],"[Q911554, Q557880, Q3427922, Q15980158, Q13152..."
3,2019-03-29-004685,Allies expressed their support for the secreta...,President Donald Trump,Q22686,2019-03-29 00:25:02,2,"[[President Donald Trump, 0.6996], [None, 0.23...",[https://www.brecorder.com/2019/03/29/484053/n...,E,[Q6581097],[+1946-06-14T00:00:00Z],"[Q911554, Q557880, Q3427922, Q15980158, Q13152..."
4,2019-07-23-003672,"And if I can help, I would love to be a mediator.",Donald Trump,Q22686,2019-07-23 14:52:24,1,"[[Donald Trump, 0.8156], [None, 0.1516], [Imra...",[http://vanityfair.com/news/2019/07/trump-modi...,E,[Q6581097],[+1946-06-14T00:00:00Z],"[Q911554, Q557880, Q3427922, Q15980158, Q13152..."
...,...,...,...,...,...,...,...,...,...,...,...,...
79674,2019-11-26-029822,I didn't want to live with that threat anymore...,Ken Morgan,Q20640866,2019-11-26 16:38:05,1,"[[Ken Morgan, 0.7476], [None, 0.2524]]",[http://sfgate.com/news/article/One-city-s-pla...,E,[Q6581097],[+1951-09-10T00:00:00Z],[Q82955]
79675,2019-10-21-026913,I do it because I'm a servant to my Lord and S...,Mark Freeman,Q42328428,2019-10-21 17:08:09,1,"[[Mark Freeman, 0.9205], [None, 0.0795]]",[https://www.wtvy.com/content/news/DAWC-Man-an...,E,[Q6581097],None,[Q33231]
79676,2019-02-14-034000,"I do not think we're there yet,",Raymond Thomas,Q22761566,2019-02-14 12:17:52,15,"[[Raymond Thomas, 0.7598], [None, 0.1201], [Jo...",[https://www.breitbart.com/news/top-general-wo...,E,[Q6581097],[+1956-12-19T00:00:00Z],[Q33999]
79677,2019-01-11-027559,I do not want a job,David Tredinnick,Q272259,2019-01-11 12:59:04,2,"[[David Tredinnick, 0.8332], [None, 0.1331], [...",[https://www.pressandjournal.co.uk/news/uk/165...,E,[Q6581097],[+1950-01-19T00:00:00Z],[Q82955]
79678,2019-09-18-074906,Samsung Galaxy M Series has proven to be a cus...,Manish Tiwary,Q16222093,2019-09-18 10:18:36,1,"[[Manish Tiwary, 0.853], [None, 0.147]]",[https://www.indiablooms.com/finance-details/1...,E,[Q6581097],[+1982-09-10T00:00:00Z],[Q2526255]

In [8]:
#Creation of a json file from df_new
df_new.to_json(RETURN_FILE_DATA)