In [1]:
import pandas as pd
import bz2
import json
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter

In [2]:
DATA_FOLDER = 'data/'
RETURN_FILE_DATA = DATA_FOLDER+"known_speaker_gender_only_male_female.json.bz2"

In [3]:
GENDER_DICT = DATA_FOLDER + "dict_genders.json"
OCC_DICT = DATA_FOLDER + "dict_occupations.json"
CAT_OCC_DICT = DATA_FOLDER + "dict_categories_occupations.json"

In [4]:
with open(GENDER_DICT) as json_file:
    gender_dict = json.load(json_file)
with open(OCC_DICT) as json_file:
    occ_dict = json.load(json_file)
with open(CAT_OCC_DICT) as json_file:
    cat_occ_dict = json.load(json_file)

In [5]:
df = pd.read_json(RETURN_FILE_DATA)

Find the gender in the gender dictionnary

In [6]:
df['gender'] = [gender_dict[x] for x in df.gender.to_list()]

In [7]:
df.shape[0]

68127

Drop the informations that are no use for us

In [8]:
df.drop(columns = ['quoteID','probas','urls','phase'], inplace=True);

Drop the speakers with no occupation

In [9]:
df.dropna(axis = 0, subset = ['occupation'], inplace = True)
df.shape[0]

65950

# **CODE** si on garde que la première occupation

Keep only the first occupation of each speaker and read it thanks to the occupation dictionnary

In [10]:
df['occupation'] = df['occupation'].apply(lambda x: x[0])

In [11]:
for idx, row in df.iterrows():
        if row['occupation'] not in occ_dict.keys():
            df.drop(idx, inplace=True)

In [12]:
df['occupation'] = [occ_dict[x] for x in df.occupation.to_list()]

Create a new colums which puts the occupations into categories of occupations

In [13]:
df['categorie'] = 0

In [14]:
for idx, row in df.iterrows():
    if row['occupation'] not in cat_occ_dict.keys():
        df.categorie[idx]='Autre'
    else:
        df.categorie[idx]=cat_occ_dict[df.occupation[idx]]

<ipython-input-14-e94b9c8c3ae5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.categorie[idx]='Autre'
/Users/potdevinjosephine/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
<ipython-input-14-e94b9c8c3ae5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.categorie[idx]=cat_occ_dict[df.occupation[idx]]

# **CODE** pour les années

Retrieve the year difference between the date of birth of the speaker and the appearence of his citation in the journals

In [15]:
df.dropna(axis = 0, subset = ['date_of_birth'], inplace = True)
df['date_of_birth'] = df['date_of_birth'].apply(lambda x: x[0][1:5])

In [16]:
df['year_of_age'] = 0
for idx, row in df.iterrows():
    df['year_of_age'][idx]=(df.date[idx].year-int(df.date_of_birth[idx]))

<ipython-input-16-0105ae3884af>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year_of_age'][idx]=(df.date[idx].year-int(df.date_of_birth[idx]))

In [17]:
df.drop(columns='date_of_birth', inplace=True)

As, every information needed is now in the DataFrame df, it is useful to sort it by the categories of occupation.

In [18]:
df.sort_values('categorie', inplace=True)
df.shape[0]

58932

In [19]:
df

,quotation,speaker,qids,date,numOccurrences,gender,occupation,categorie,year_of_age
99401,Samsung Galaxy M Series has proven to be a cus...,Manish Tiwary,Q16222093,2019-09-18 10:18:36,1,male,film director,Artist,37
18099,[ Kevin Feige ] wanted to make sure we didn't ...,Christopher Markus,Q5112818,2019-08-03 16:30:57,1,male,screenwriter,Artist,19
18101,Further consideration will be given at this st...,Christopher Morgan,Q22348394,2019-05-30 06:00:00,3,male,film producer,Artist,77
18102,harm in this case is great,Christopher Morgan,Q22348394,2019-02-06 03:27:39,7,male,film producer,Artist,77
58209,Where Sekiro varies a bit is in having a confl...,Ian Hamilton,Q15446774,2019-04-08 02:10:49,1,male,writer,Artist,73
...,...,...,...,...,...,...,...,...,...
60481,"Let's put the breaks on the excitement here,",Remi Garde,Q12160,2019-03-08 07:27:00,12,male,association football player,Sports,53
60478,Let's keep it one thousand up here because my ...,Marcellus Wiley,Q16205555,2019-08-21 01:52:25,1,male,American football player,Sports,45
60465,Let's be honest. The town centre has had its d...,Joe Robertson,Q16875101,2019-11-28 05:02:17,2,male,ice hockey player,Sports,71
60498,"If Pukki had been playing for them, they would...",Paul Merson,Q430740,2019-08-20 10:06:00,2,male,association football player,Sports,51
48717,"It was the culmination of our trip,",Mark Smith,Q10502635,2019-08-30 15:01:00,1,male,association football player,Sports,55

In [20]:
df_final = df.groupby(df.categorie)

In [21]:
df_final.head()

,quotation,speaker,qids,date,numOccurrences,gender,occupation,categorie,year_of_age
99401,Samsung Galaxy M Series has proven to be a cus...,Manish Tiwary,Q16222093,2019-09-18 10:18:36,1,male,film director,Artist,37
18099,[ Kevin Feige ] wanted to make sure we didn't ...,Christopher Markus,Q5112818,2019-08-03 16:30:57,1,male,screenwriter,Artist,19
18101,Further consideration will be given at this st...,Christopher Morgan,Q22348394,2019-05-30 06:00:00,3,male,film producer,Artist,77
18102,harm in this case is great,Christopher Morgan,Q22348394,2019-02-06 03:27:39,7,male,film producer,Artist,77
58209,Where Sekiro varies a bit is in having a confl...,Ian Hamilton,Q15446774,2019-04-08 02:10:49,1,male,writer,Artist,73
89843,"We can't remove debris to a landfill, for exam...",Renee Sanders,Q2608942,2019-03-27 18:20:26,1,female,documentary filmmaker,Autre,69
43565,Who is the greatest competitor?,Mark Henry,Q310073,2019-02-17 10:13:41,1,male,weightlifter,Autre,48
31641,My dad coached Nika and Erika a while back and...,James Bailey,Q11727178,2019-05-24 10:05:00,1,male,middle-distance runner,Autre,90
31089,Or there's been a point where we lapse for 20 ...,Aidan Ryan,Q4696734,2019-06-18 00:30:00,1,male,hurler,Autre,33
90041,It's been throughout the entire Washington Str...,Stephen Archer,Q7608598,2019-01-28 10:19:20,1,male,rugby player,Autre,31
26239,"Given the seriousness of these issues, which b...",Steven Mnuchin,Q24248265,2019-04-11 15:23:37,2,male,banker,Business & Law,57
94606,The bifurcation of winners and losers is what ...,Brian Cornell,Q20857886,2019-05-22 18:00:00,2,male,entrepreneur,Business & Law,59
26238,Cuba continues to play a destabilizing role in...,Steven Mnuchin,Q24248265,2019-06-07 20:34:14,4,male,banker,Business & Law,57
60583,so impressed with how @LibertyU students condu...,Jerry Falwell Jr. .,Q6183563,2019-09-13 19:00:28,13,male,lawyer,Business & Law,57
60585,"continues to provide generous, reasonable, and...",David McKeague,Q5237389,2019-05-24 12:00:45,1,male,lawyer,Business & Law,73
51228,We believe it is inevitable more free games wi...,Timothy O'Shea,Q7807430,2019-02-13 21:20:40,1,male,teacher,Education,70
89416,This is a great club with a lot of history and...,Jack Harrison,Q16018779,2019-04-15 00:00:00,3,male,teacher,Education,107
97251,From Norman Cousins to Susan Sontag to Jimmy a...,FRANK MCCOURT,Q208869,2019-02-22 13:31:32,1,male,teacher,Education,89
45123,Dikgang Moseneke brings vast experience in hum...,Judith Kelley,Q16197032,2019-11-22 16:38:21,1,female,academic,Education,52
45880,We must bring back tougher international restr...,Robert Palladino,Q23562589,2019-02-07 22:37:50,9,male,academic,Education,87
34940,Do they even have to make such a delineation?,Michael Collins,Q104859,2019-09-06 14:17:08,1,male,military officer,Military,89
14215,our enablement and our assistance,Joseph Votel,Q4126786,2019-02-15 12:29:22,2,male,military officer,Military,61
11823,There are currently more job openings than peo...,Sonny Perdue,Q525362,2019-12-06 10:55:01,1,male,military officer,Military,73
76583,as close as possible to adversaries and their ...,Paul Nakasone,Q29630813,2019-05-28 11:50:02,2,male,military officer,Military,56
14802,This is the true and objective way in which yo...,Muhammadu Buhari,Q361567,2019-03-29 12:38:18,4,male,military personnel,Military,77
32772,So I had never thought about those things to b...,Erin O'Connor,Q1884047,2019-04-29 23:43:00,1,female,model,Model,41
39859,I hope that it's going to change for the bette...,Natalie Portman,Q37876,2019-02-20 03:33:50,1,female,model,Model,38
7391,"Batman v Superman: Dawn of Justice, Justice Le...",Henry Cavill,Q295498,2019-06-28 08:54:41,1,male,model,Model,36
1663,"Blessed beyond words. Thank you, God. I believ...",Kylie Jenner,Q1770624,2019-06-03 04:20:00,13,female,model,Model,22
1667,I know you won't remember much about the first...,kylie jenner,Q1770624,2019-02-01 18:11:06,3,female,model,Model,22
12483,My view is very clear: removing maintenance gr...,pm THERESA May,Q264766,2019-05-29 21:30:52,1,female,politician,Politics,63
53426,deeply troubled by the case.,Chris Hipkins,Q5106890,2019-09-25 19:29:57,1,male,politician,Politics,41
12478,This is an issue of grave importance for the f...,Prime Minister Theresa May,Q264766,2019-03-12 21:44:00,1,female,politician,Politics,63
80931,"For instance, villages that cast 80 percent vo...",Varun Gandhi,Q2728775,2019-04-15 10:21:39,1,male,politician,Politics,39
14648,The UN-brokered Stockholm Agreement reached in...,António Guterres,Q311440,2019-02-26 16:07:41,1,male,politician,Politics,70
44530,"see no decent people in this state, let them e...",Michel Aoun,Q3308880,2019-11-18 13:48:06,1,male,Catholic priest,Religion,60
92094,"I also urge you to be kind to one another, and...",Joseph M. McShane,Q6285147,2019-04-14 22:43:18,4,male,theologian,Religion,70
53164,"Putting the sick at the center means, among ot...",Pietro Parolin,Q574058,2019-03-19 09:18:08,2,male,Catholic priest,Religion,64
46601,respect with gratitude the material and spirit...,Cardinal Raymond Burke,Q515887,2019-05-24 00:00:00,1,male,Catholic priest,Religion,71
98025,I want to carefully consider the issues that h...,Patrick McKinney,Q19914201,2019-12-30 00:00:00,5,male,Catholic priest,Religion,65
53571,Showfields is at the intersection of tradition...,Katie Hunt,Q20986765,2019-06-30 13:56:00,2,female,chemist,Scientist,64
82873,this mission is another that adds to our proud...,Daniel Hershkowitz,Q2613034,2019-07-01 21:32:02,1,male,mathematician,Scientist,66
47116,"So, we have to respect the decision of the court,",Wee Ka Siong,Q7979293,2019-11-07 14:21:00,1,male,engineer,Scientist,51
47118,Does Syed Saddiq realise that JPA is an agency...,Wee Ka Siong,Q7979293,2019-12-26 11:04:01,1,male,engineer,Scientist,51
46856,How are you going to bring everybody along the...,Peter Orris,Q30110263,2019-06-11 02:52:00,1,male,physician,Scientist,74
52150,No matter what may unfold in her story let's a...,Elizabeth Smart,Q13462978,2019-01-11 00:00:00,5,female,historian,Social Sciences,32
90049,modernism on the hoof: startling formal innova...,James Kaplan,Q6137097,2019-11-19 21:00:05,2,male,journalist,Social Sciences,68
52149,"A lot of the things that I went through, I was...",Elizabeth Smart,Q13462978,2019-01-14 00:00:00,3,female,historian,Social Sciences,32
94595,"The area is remote, rarely seen by outsiders,",Cynthia McFadden,Q5200121,2019-11-18 12:49:59,1,female,journalist,Social Sciences,63
86599,"If there's a motivated team, it's Los Angeles,",Elliotte Friedman,Q5365754,2019-12-19 18:09:56,1,male,journalist,Social Sciences,49
77571,There will be a great buzz on opening day and ...,Paul Baldwin,Q7149189,2019-10-31 13:26:00,4,male,cricketer,Sports,46
80131,It's going to be a great day for shooting exte...,Mike Alexander,Q4107568,2019-12-28 00:00:00,1,male,American football player,Sports,54
77652,These are folks who are spending their own mon...,Bob Stephen,Q4934082,2019-09-10 00:00:00,1,male,Canadian football player,Sports,61
80130,"As of yet, we have been ignored by the HSE and...",Liam Moore,Q6539724,2019-02-27 09:26:00,1,male,association football player,Sports,26
77661,Playing for the country is always special. We ...,Gurpreet Singh Sandhu,Q5620263,2019-01-05 14:31:24,1,male,association football player,Sports,27

# **CODE** si on regarde toutes les occupations

In [22]:
#for idx, row in df.iterrows():
#    x=0
 #   for i in range(len(row['occupation'])):
  #      if row['occupation'][i-x] not in occ_dict.keys():
   #         row['occupation'].remove(row['occupation'][i-x])
    #        x+=1

In [23]:
#for idx, row in df.iterrows():
 #   for i in range(len(row['occupation'])):
  #      row['occupation'][i]=occ_dict[row['occupation'][i]]

In [24]:
#df

# Problemes avec ce code et améliorations a faire

**1-** Il n'y a que des boucles for ou même des doubles boucles for. Le code marche mais (pour moi) il met du temps à run et il n'est surement pas optimisé

**2-** Je ne sais pas exactement quoi faire à la fin: retourner un groupby; retrouner df_final qui a sort les occupations; faire un sort_values sur quelque chose d'autre de plus pertinant?

**3-** Il faut que je fasse la même chose pour quand on garde toutes les occupations d'un speaker. Idée: mettre dans la colonne 'catégorie' une liste des catégories pour chaque occupation et ne garder à la fin dans la cellule, que la catégorie qui revient le plus.